baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'The Church of Chuck - Podcast'
theme = "castanet"
googleAnalytics = ""
themesdir = "../.."
paginate = "9"
buildFuture = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

#[[Menu.Main]]
#    name = "Contact"
#    identifier = "contact"
#    url = "/contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

#[[Menu.Main]]
#    name = "Guests"
#    identifier = "guests"
#    url = "/guest"

#[[Menu.Main]]
#    name = "Upcoming Episodes"
#    identifier = "upcoming"
#    url = "/upcoming"

#[[Menu.Main]]
#    name = "Blog"
#    identifier = "blog"
#    url = "/blog"

#[[Menu.Main]]
#    name = "Resources"
#    identifier = "resources"
#    url = "#!"

#[[Menu.Main]]
#    name = "Books"
#    identifier = "books"
#    url = "/books"
#    parent = "resources"
#[[Menu.Main]]
#    name = "Podcasts"
#    identifier = "podcasts"
#    url = "/books"
#    parent = "resources"
#[[Menu.Main]]
#    name = "Internet"
#    identifier = "internet"
#    url = "https://www.google.com"

[params]
googleAnalytics_UA = ""
mainSections = ["episode"]
episode_number_style  = "brackets"
episode_number_prefix = "CWC"
site_theme = "blue"
# site_layout = "grid"
site_layout = "row"
show_next_upcoming = "true"
enable_jumbo = "true"
# enable_jumbo = "false"
disable_title_caps = "true"
# truncate = "100"
# about_logo = "/img/hugocast.png"
copyright_notice = ""
#youtube_subscribe = ""
#itunes_subscribe = ""
#android_subscribe = ""
spotify_subscribe = "https://open.spotify.com/show/25SmtmaRsodVXxcboxGj6R?si=347b12fabd1b42fa"
#google_play_subscribe = ""
#stitcher_subscribe = ""
#soundcloud_subscribe = ""
#pocketcasts_subscribe = ""
#mailchimp_subscribe = ""
# rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Not a real church, just a group of idiots talking about stuff that we like or don't like, and hopefully interests you"
media_prefix = ""
#disqusShortname = ""
  [params.feed]
    copyright = "" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "" #no markdown or HTML
    itunes_author = "" #no markdown or HTML
    itunes_summary = "" # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = ""
    itunes_owner_email = "" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
    itunes_image = "" #fqdn to the image art for your podcast
    itunes_top_category = ""
    itunes_first_sub_category = ""
    itunes_second_sub_category = ""
    language = "en-us"

  [params.realfavicongenerator] # https://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
    msapplication_tilecolor="#2b5797"
    theme_color="#ffffff"

  [params.podlove] # https://subscribe-button.podlove.org
    subscribe_title = "The Church of Chuck - Podcast"              # fallback: site title from above
    subscribe_subtitle = "Just a group of idiots talking about stuff"           # fallback: ""
    subscribe_description = "Not a real church, just a group of idiots talking about stuff that we like or don't like, and hopefully interests you"        # fallback: ""
    subscribe_cover = "img/logo.jpg"  # fallback: ""
    subscribe_color = "#585e6c"       # fallback: ""
    subscribe_size = "medium"         # options: small, medium, big
    subscribe_format = "rectangle"    # options: rectangle, square, cover
    subscribe_style = "filled"        # options: filled, outline, frameless
    subscribe_language = "en"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
    subscribe_feed_type = "audio"     # options: audio, video
    subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  # Social links can be given in full URL form or short form
  # In the short form the theme will generate a relevant URL
  [params.social]
    github = "cutthroat78/churchforchuck-podcast-website"
    #gitlab = "mattstratton"
    #facebook = "Arresteddevops"
    #facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    #twitter = "https://twitter.com/arresteddevops"
    #twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    #pinterest = "nozzleio"
    #instagram = "nozzleio"
    #youtube = "arresteddevops"
    # Short form in linkedin will link to a user's page so use long form for company pages
    #linkedin = "https://www.linkedin.com/company/linkedin/"
    #linkedin = "mattstratton"
    #twitch = "mattstratton"
    #mastodon = "https://hachyderm.io/@mattstratton"

  [params.authors]
    [params.authors.person]
      name = ""
      thumbnail = "img/host/_.png"
      bio = ""
      [params.authors.person.social]
        #homepage = "https://www.mattstratton.io"
        #github = "mattstratton"
        #facebook = "matt.stratton"
        #twitter = "mattstratton"
        #linkedin = "mattstratton"
        #pinterest = "mattstratton"
        #instagram = "instagram"
        #youtube = "mattstratton"
        #twitch = "mattstratton"

    [params.links]
      [params.links.link]
        name = "_"
        url = "https://www.google.com"
